# Serverless configuration file

service: vivai-app-dev

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:GetObjectTagging"
        - "s3:GetObjectAcl"
        - "s3:GetObjectVersion"
        - "s3:PutObject"
        - "s3:PutObjectTagging"
        - "s3:PutObjectAcl"
        - "s3:DeleteObject"
        - "s3:DeleteObjectTagging"
        - "s3:PutBucketCORS"
        - "s3:ListBucket"
        - "s3:HeadBucket"
        - "s3:ListAllMyBuckets"
        - "s3:ListBucketVersions"
      Resource: "*"

    - Effect: "Allow" # Aurora Serverless Data API - Secret
      Action:
        - "secretsmanager:GetSecretValue"
        - "secretsmanager:PutResourcePolicy"
        - "secretsmanager:PutSecretValue"
        - "secretsmanager:DeleteSecret"
        - "secretsmanager:DescribeSecret"
        - "secretsmanager:TagResource"
      Resource:
        - '*'

    - Effect: "Allow" # Aurora Serverless Data API
      Action:
        - "rds-data:BeginTransaction"
        - "rds-data:CommitTransaction"
        - "rds-data:ExecuteStatement"
        - "rds-data:RollbackTransaction"
      Resource: "*"


functions:
  app:
    handler: wsgi_handler.handler
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: app
          method: ANY
          cors: true
      - http: 
          path: 'app/{proxy+}'
          method: ANY
          cors: true

package:
  include:
    - common/**
  exclude:
    - tests/**
    - venv/**
    - .git/**

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.APP
    packRequirements: false
  pythonRequirements:
    layer: true
    noDeploy:
      - pip
